# Data Quality Assessment

In [2]:
import pandas as pd

df = pd.read_csv("customer_churn.csv")
df.head()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.10,2394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.50,3796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes

### 1. Missing Values

A missing value is a value that is not available or has not been recorded for a particular observation.

In Pandas, missing values are commonly represented as: NaN

Example:

Suppose a telecom company's customer data looks like:

| Customer | Age | Monthly Charges |
| -------- | --: | --------------: |
| C001     |  25 |            50.5 |
| C002     | NaN |            70.2 |
| C003     |  32 |             NaN |

Here, the age of C002 and monthly charge of C003 are missing.

#### AI/ML usage

Missing values are important because many ML algorithms cannot directly work with missing values.

Common solutions include:

* Removing rows
* Removing columns
* Mean/median imputation
* Mode imputation
* Forward/backward filling
* Model-based imputation

### 2. Number of Missing Values

In [3]:
missing_count = df.isnull().sum()

print(missing_count)

CustomerID           0
Age                 51
Gender               0
TenureYears          0
MonthlyCharges      50
TotalCharges        51
ContractType         0
InternetService      0
PaymentMethod        0
SeniorCitizen        0
SupportCalls         0
StreamingService     0
PaperlessBilling     0
Churn                0
dtype: int64

### 3. Total Number of Missing Values

The total number of missing values is the sum of all missing cells across the entire dataset.

In [4]:
total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 152

### 4. Percentage of Missing Values

Missing-value percentage tells us what percentage of the values in a column are missing.

Formula:

Missing Percentage = (Number of Missing Values /bTotal Number of Rows) ×100

In [5]:
missing_percentage = df.isnull().mean() * 100

print(missing_percentage)

CustomerID          0.000000
Age                 1.015936
Gender              0.000000
TenureYears         0.000000
MonthlyCharges      0.996016
TotalCharges        1.015936
ContractType        0.000000
InternetService     0.000000
PaymentMethod       0.000000
SeniorCitizen       0.000000
SupportCalls        0.000000
StreamingService    0.000000
PaperlessBilling    0.000000
Churn               0.000000
dtype: float64

### 5. Missing Values by Column

Missing values by column tells us which columns contain missing data and how much.

In [8]:
missing_by_column = df.isnull().sum()

missing_by_column = missing_by_column[missing_by_column > 0]
print(missing_by_column)

Age               51
MonthlyCharges    50
TotalCharges      51
dtype: int64

### 6. Missing Value Patterns

A missing-value pattern shows whether missing values occur randomly, together, or in particular groups of records.

For example:

Customer A → Age missing

Customer B → MonthlyCharges missing

Customer C → Age + TotalCharges missing

Understanding patterns can help determine why values are missing.

#### AI/ML usage

Missing-value patterns can indicate:

* Data collection problems
* System errors
* Optional fields
* Customer behavior
* Potential bias

Before deciding on imputation, we should understand the pattern.

In [9]:
df[df.isnull().any(axis=1)]

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
33,CUST00034,45.0,Female,6,NaN,9383.95,One year,Fiber optic,Electronic check,No,0,No,Yes,No
46,CUST00047,56.0,Male,2,21.50,NaN,Month-to-month,No,Bank transfer,No,0,Yes,No,No
94,CUST00095,43.0,Female,4,43.41,NaN,One year,DSL,Bank transfer,No,0,Yes,Yes,No
97,CUST00098,NaN,Female,5,32.44,2065.67,Month-to-month,DSL,Mailed check,No,2,Yes,No,No
101,CUST00102,18.0,Male,3,NaN,2472.61,One year,No,Bank transfer,No,2,Yes,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4822,CUST04823,41.0,Male,7,66.38,NaN,Month-to-month,Fiber optic,Mailed check,No,3,Yes,Yes,No
4832,CUST04833,44.0,Male,5,NaN,1736.51,Two year,Fiber optic,Credit card,No,3,Yes,No,No
4834,CUST04835,23.0,Male,5,NaN,1950.27,Month-to-month,DSL,Mailed check,No,4,No,No,Yes
5002,CUST03625,NaN,Female,9,51.74,6196.95,Month-to-month,Fiber optic,Mailed check,Yes,3,No,Yes,No
5012,CUST02962,53.0,Female,6,85.98,NaN,Month-to-month,No,Credit card,No,4,Yes,No,Yes

In [13]:
# Find rows where multiple values are missing

df[df.isnull().sum(axis=1) > 1]

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn,Missing_Count
622,CUST00623,NaN,Female,9,NaN,4165.94,Month-to-month,Fiber optic,Bank transfer,No,2,No,Yes,Yes,2
2046,CUST02047,NaN,Male,3,31.11,NaN,Two year,No,Mailed check,No,3,Yes,No,No,2
2457,CUST02458,NaN,Male,3,51.08,NaN,Month-to-month,DSL,Credit card,No,0,No,No,No,2

### 7. Duplicate Records

A duplicate record is a row that appears more than once in the dataset.

Example:

A customer might accidentally be entered twice:

| CustomerID | Age | Churn |
| ---------- | --: | ----- |
| C001       |  25 | No    |
| C001       |  25 | No    |

The second row is a duplicate.

#### AI/ML usage

Duplicates can cause problems because they may:

* Bias statistics
* Overrepresent certain customers
* Affect model training
* Cause data leakage in some situations

### 8. Identify Duplicates

In [14]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5015     True
5016     True
5017     True
5018     True
5019     True
Length: 5020, dtype: bool

True means that the row is a duplicate of an earlier row.

### 9. Count Duplicates

In [15]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 20

### 10. Identify Completely Duplicated Rows

A completely duplicated row means every value across all columns is identical to another row.

In [16]:
complete_duplicates = df[df.duplicated(keep=False)]

print(complete_duplicates)

     CustomerID   Age  Gender  TenureYears  MonthlyCharges  TotalCharges  \
615   CUST00616  49.0    Male            6           32.29       2588.15
640   CUST00641  36.0  Female            9           71.92       8511.32
757   CUST00758  20.0  Female            1          115.78       2574.96
1868  CUST01869  29.0    Male            8           60.27       5884.26
2366  CUST02367  63.0    Male            6          111.09       8967.34
2755  CUST02756  29.0    Male            8           28.23       3021.45
2827  CUST02828  55.0    Male            4           70.71       3554.79
2916  CUST02917  38.0  Female            0          103.30        662.96
2961  CUST02962  53.0  Female            6           85.98           NaN
3215  CUST03216  67.0    Male            2           62.74       2202.74
3235  CUST03236  39.0  Female            8           93.76       9612.62
3335  CUST03336  55.0  Female            3           44.33       2007.54
3406  CUST03407  33.0    Male            4          102.74       5490.42
3484  CUST03485  43.0    Male           10          117.65      15278.80
3527  CUST03528  32.0  Female            5           38.43       2739.80
3624  CUST03625   NaN  Female            9           51.74       6196.95
3708  CUST03709  66.0    Male            2           34.41       1200.43
4301  CUST04302  55.0    Male            9           21.57       2367.15
4392  CUST04393  24.0    Male            5           84.63       6005.95
4544  CUST04545  25.0    Male            6          106.68       8658.90
5000  CUST03407  33.0    Male            4          102.74       5490.42
5001  CUST00758  20.0  Female            1          115.78       2574.96
5002  CUST03625   NaN  Female            9           51.74       6196.95
5003  CUST04545  25.0    Male            6          106.68       8658.90
5004  CUST03236  39.0  Female            8           93.76       9612.62
5005  CUST01869  29.0    Male            8           60.27       5884.26
5006  CUST02917  38.0  Female            0          103.30        662.96
5007  CUST03336  55.0  Female            3           44.33       2007.54
5008  CUST03528  32.0  Female            5           38.43       2739.80
5009  CUST02828  55.0    Male            4           70.71       3554.79
5010  CUST04393  24.0    Male            5           84.63       6005.95
5011  CUST03485  43.0    Male           10          117.65      15278.80
5012  CUST02962  53.0  Female            6           85.98           NaN
5013  CUST03216  67.0    Male            2           62.74       2202.74
5014  CUST04302  55.0    Male            9           21.57       2367.15
5015  CUST00616  49.0    Male            6           32.29       2588.15
5016  CUST00641  36.0  Female            9           71.92       8511.32
5017  CUST03709  66.0    Male            2           34.41       1200.43
5018  CUST02367  63.0    Male            6          111.09       8967.34
5019  CUST02756  29.0    Male            8           28.23       3021.45

        ContractType InternetService     PaymentMethod SeniorCitizen  \
615         One year             DSL      Mailed check            No
640   Month-to-month              No     Bank transfer            No
757   Month-to-month              No      Mailed check            No
1868        One year     Fiber optic     Bank transfer            No
2366        Two year             DSL  Electronic check           Yes
2755        One year     Fiber optic       Credit card            No
2827        One year             DSL       Credit card            No
2916  Month-to-month             DSL  Electronic check            No
2961  Month-to-month              No       Credit card            No
3215        One year     Fiber optic     Bank transfer           Yes
3235        Two year             DSL       Credit card            No
3335        Two year              No     Bank transfer            No
3406        Two year             DSL  Electronic check            No
3484        One year     Fiber optic       Credit card            No
3527        Two year     Fiber optic     Bank transfer            No
3624  Month-to-month     Fiber optic      Mailed check           Yes
3708        Two year     Fiber optic       Credit card           Yes
4301  Month-to-month              No     Bank transfer            No
4392        Two year              No      Mailed check            No
4544        One year     Fiber optic      Mailed check            No
5000        Two year             DSL  Electronic check            No
5001  Month-to-month              No      Mailed check            No
5002  Month-to-month     Fiber optic      Mailed check           Yes
5003        One year     Fiber optic      Mailed check            No
5004        Two year             DSL       Credit card            No
5005        One year     Fiber optic     Bank transfer            No
5006  Month-to-month             DSL  Electronic check            No
5007        Two year              No     Bank transfer            No
5008        Two year     Fiber optic     Bank transfer            No
5009        One year             DSL       Credit card            No
5010        Two year              No      Mailed check            No
5011        One year     Fiber optic       Credit card            No
5012  Month-to-month              No       Credit card            No
5013        One year     Fiber optic     Bank transfer           Yes
5014  Month-to-month              No     Bank transfer            No
5015        One year             DSL      Mailed check            No
5016  Month-to-month              No     Bank transfer            No
5017        Two year     Fiber optic       Credit card           Yes
5018        Two year             DSL  Electronic check           Yes
5019        One year     Fiber optic       Credit card            No

      SupportCalls StreamingService PaperlessBilling Churn  Missing_Count
615              3               No              Yes   Yes              0
640              5               No              Yes    No              0
757              1              Yes              Yes    No              0
1868             2               No              Yes    No              0
2366             1               No              Yes    No              0
2755             0              Yes              Yes    No              0
2827             3              Yes               No    No              0
2916             2               No              Yes   Yes              0
2961             4              Yes               No   Yes              1
3215             2               No              Yes    No              0
3235             2               No               No    No              0
3335             1              Yes              Yes    No              0
3406             1               No               No    No              0
3484             0              Yes               No   Yes              0
3527             4              Yes               No   Yes              0
3624             3               No              Yes    No              1
3708             1              Yes               No    No              0
4301             2              Yes               No    No              0
4392             0              Yes              Yes    No              0
4544             1               No               No   Yes              0
5000             1               No               No    No              0
5001             1              Yes              Yes    No              0
5002             3               No              Yes    No              1
5003             1               No               No   Yes              0
5004             2               No               No    No              0
5005             2               No              Yes    No              0
5006             2               No              Yes   Yes              0
5007             1              Yes              Yes    No              0
5008             4              Yes               No   Yes              0
5009             3              Yes               No    No              0
5010             0              Yes              Yes    No              0
5011             0              Yes               No   Yes              0
5012             4              Yes               No   Yes              1
5013             2               No              Yes    No              0
5014             2              Yes               No    No              0
5015             3               No              Yes   Yes              0
5016             5               No              Yes    No              0
5017             1              Yes               No    No              0
5018             1               No              Yes    No              0
5019             0              Yes              Yes    No              0

keep=False marks all copies of the duplicate instead of marking only the second occurrence.

In [17]:
print(
    "Rows involved in complete duplication:",
    df.duplicated(keep=False).sum()
)

Rows involved in complete duplication: 40

### 11. Potential Duplicate Records

A potential duplicate is a record that may represent the same entity even though the entire row is not identical.

For example:

| CustomerID | Age | Gender |
| ---------- | --: | ------ |
| C001       |  25 | Female |
| C001       |  25 | female |

These aren't completely identical because of capitalization, but they may represent the same customer.

In [18]:
df["CustomerID"].duplicated().sum()

np.int64(20)

### 12. Negative Values Where Inappropriate

Some variables cannot logically be negative.

For your dataset:

* Age → cannot be negative
* TenureYears → cannot be negative
* MonthlyCharges → cannot be negative
* TotalCharges → cannot be negative
* SupportCalls → cannot be negative

In [19]:
# Check Age
df[df["Age"] < 0]

Empty DataFrame
Columns: [CustomerID, Age, Gender, TenureYears, MonthlyCharges, TotalCharges, ContractType, InternetService, PaymentMethod, SeniorCitizen, SupportCalls, StreamingService, PaperlessBilling, Churn, Missing_Count]
Index: []

In [20]:
# Check Tenure
df[df["TenureYears"] < 0]

Empty DataFrame
Columns: [CustomerID, Age, Gender, TenureYears, MonthlyCharges, TotalCharges, ContractType, InternetService, PaymentMethod, SeniorCitizen, SupportCalls, StreamingService, PaperlessBilling, Churn, Missing_Count]
Index: []

In [21]:
# Check Monthly Charges
df[df["MonthlyCharges"] < 0]

Empty DataFrame
Columns: [CustomerID, Age, Gender, TenureYears, MonthlyCharges, TotalCharges, ContractType, InternetService, PaymentMethod, SeniorCitizen, SupportCalls, StreamingService, PaperlessBilling, Churn, Missing_Count]
Index: []

In [22]:
# Check Total Charges
df[df["TotalCharges"] < 0]

Empty DataFrame
Columns: [CustomerID, Age, Gender, TenureYears, MonthlyCharges, TotalCharges, ContractType, InternetService, PaymentMethod, SeniorCitizen, SupportCalls, StreamingService, PaperlessBilling, Churn, Missing_Count]
Index: []

In [23]:
# Check Support Calls
df[df["SupportCalls"] < 0]

Empty DataFrame
Columns: [CustomerID, Age, Gender, TenureYears, MonthlyCharges, TotalCharges, ContractType, InternetService, PaymentMethod, SeniorCitizen, SupportCalls, StreamingService, PaperlessBilling, Churn, Missing_Count]
Index: []

### 13. Impossible Values

An impossible value is a value that falls outside a logically reasonable range.

For example:

Age = 500

Age = -20

SupportCalls = -3

In [24]:
df[(df["Age"] < 0) | (df["Age"] > 120)]

Empty DataFrame
Columns: [CustomerID, Age, Gender, TenureYears, MonthlyCharges, TotalCharges, ContractType, InternetService, PaymentMethod, SeniorCitizen, SupportCalls, StreamingService, PaperlessBilling, Churn, Missing_Count]
Index: []

### 14. Incorrect Categories

Incorrect categories occur when categorical values don't follow the expected category list.

For example:

Expected: Female, Male

Actual: Female, Male, female

Here female is an inconsistent category.

In [25]:
df["Gender"].value_counts()

Gender
Female    2521
Male      2498
female       1
Name: count, dtype: int64

### 15. Invalid Dates

An invalid date is a date that:

* Doesn't follow the required format
* Doesn't exist
* Falls outside an expected range

Examples:

2026-02-30

2025-15-50

abc

In [26]:
datetime_columns = df.select_dtypes(
    include=["datetime64"]
).columns

print(datetime_columns)

Index([], dtype='str')

### 16. Incorrect Data Types

Incorrect data type means a column is stored in a format that doesn't match its intended meaning.

Examples:

Age stored as string → "25"

MonthlyCharges stored as string → "75.50"

Date stored as object instead of datetime

In [28]:
df.dtypes

CustomerID              str
Age                 float64
Gender                  str
TenureYears           int64
MonthlyCharges      float64
TotalCharges        float64
ContractType            str
InternetService         str
PaymentMethod           str
SeniorCitizen           str
SupportCalls          int64
StreamingService        str
PaperlessBilling        str
Churn                   str
Missing_Count         int64
dtype: object

### 17. Unexpected Values

Unexpected values are values that technically exist but aren't expected according to the business rules.

For example:

Churn = "Maybe"

Gender = "Unknown"

ContractType = "Weekly"

In [31]:
categorical_columns = df.select_dtypes(include="str").columns

for column in categorical_columns:
    print("\n", column)
    print(df[column].value_counts())

 CustomerID
CustomerID
CUST00616    2
CUST00641    2
CUST00758    2
CUST01869    2
CUST02367    2
            ..
CUST04996    1
CUST04997    1
CUST04998    1
CUST04999    1
CUST05000    1
Name: count, Length: 5000, dtype: int64

 Gender
Gender
Female    2521
Male      2498
female       1
Name: count, dtype: int64

 ContractType
ContractType
Month-to-month    2756
One year          1240
Two year          1023
Month to month       1
Name: count, dtype: int64

 InternetService
InternetService
Fiber optic    2253
DSL            1734
No             1032
fiber optic       1
Name: count, dtype: int64

 PaymentMethod
PaymentMethod
Mailed check        1308
Credit card         1261
Bank transfer       1248
Electronic check    1203
Name: count, dtype: int64

 SeniorCitizen
SeniorCitizen
No     4065
Yes     955
Name: count, dtype: int64

 StreamingService
StreamingService
Yes    2534
No     2486
Name: count, dtype: int64

 PaperlessBilling
PaperlessBilling
No     2536
Yes    2484
Name: count, dtype: int64

 Churn
Churn
No     3623
Yes    1397
Name: count, dtype: int64

### 18. Empty Strings

An empty string is a value such as:

""

It isn't necessarily recognized by Pandas as NaN.

In [33]:
empty_string_counts = (
    df.select_dtypes(include="str")
      .apply(lambda x: x.str.strip().eq("").sum())
)

print(empty_string_counts)

CustomerID          0
Gender              0
ContractType        0
InternetService     0
PaymentMethod       0
SeniorCitizen       0
StreamingService    0
PaperlessBilling    0
Churn               0
dtype: int64

### 19. Null-like Values

Sometimes missing data is represented using text instead of actual NaN.

Examples:

"NA"

"N/A"

"null"

"None"

"missing"

"-"

"unknown"

These are called null-like values.

In [39]:
null_like_values = [
    "",
    "NA",
    "N/A",
    "NULL",
    "null",
    "None",
    "none",
    "missing",
    "-"
]

for column in df.select_dtypes(include="str"):
    for value in null_like_values:
        count = (
            df[column]
            .astype(str)
            .str.strip()
            .eq(value)
            .sum()
        )
        
        if count > 0:
            print(column, value, count)